{% set name = "wetterdienst" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d16e3b7c23a8c37e7b91679c23712a4ee9067388b3858d789c53e7cf69eeac06

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - wetterdienst = wetterdienst.cli:run
    - wddump = wetterdienst.dwd.radar.cli:wddump

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6
    - pandas
    - numpy
    - scipy
    - h5py
    - cachetools
    - docopt
    - munch
    - dateparser
    - beautifulsoup4
    - requests
    - python-dateutil
    - dogpile.cache
    - appdirs
    - lxml
    - tqdm
    - PyPDF2
    - tabulate
    - deprecation
    - fastapi
    - pytz
    - requests-ftp
    - measurement

test:
  imports:
    - wetterdienst

about:
  home: https://github.com/earthobservations/wetterdienst
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open weather data for humans
  doc_url: https://wetterdienst.readthedocs.io/
  dev_url: https://github.com/earthobservations/wetterdienst

extra:
  recipe-maintainers:
    - kmuehlbauer
