{% set name = "wetterdienst" %}
{% set version = "0.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d07470dca82e26430be7ec9e9474431ecc5d882c57b50fb2f8ea612ca9edb4e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - wetterdienst = wetterdienst.ui.cli:cli
    - wddump = wetterdienst.provider.dwd.radar.cli:wddump

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - pandas
    - numpy
    - scipy
    - cachetools
    - dateparser
    - beautifulsoup4
    - requests
    - requests-ftp
    - python-dateutil
    - appdirs
    - lxml
    - tqdm
    - PyPDF2
    - tabulate
    - deprecation
    - importlib_metadata
    - measurement
    - rapidfuzz
    - Pint
    - aenum
    - click
    - click-params
    - cloup
    - fsspec
    - aiohttp
    # additional
    - environs
    - timezonefinder
    - scikit-learn

test:
  imports:
    - wetterdienst

about:
  home: https://github.com/earthobservations/wetterdienst
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open weather data for humans
  doc_url: https://wetterdienst.readthedocs.io/
  dev_url: https://github.com/earthobservations/wetterdienst

extra:
  recipe-maintainers:
    - amotl
    - gutzbenj
    - kmuehlbauer
