{% set name = "wetterdienst" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d2d31fdd76eeeecb15102fdcb24ec6ba17d03d0f65aff74164ac70402f5e883

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - wetterdienst = wetterdienst.ui.cli:cli
    - wddump = wetterdienst.provider.dwd.radar.cli:wddump

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6
    - pandas
    - numpy
    - scipy
    - cachetools
    - munch
    - dateparser
    - beautifulsoup4
    - requests
    - requests-ftp
    - python-dateutil
    - dogpile.cache
    - appdirs
    - lxml
    - tqdm
    - PyPDF2
    - tabulate
    - deprecation
    - importlib_metadata
    - measurement
    - rapidfuzz
    - Pint
    - aenum
    - click
    - click-params
    - cloup

test:
  imports:
    - wetterdienst

about:
  home: https://github.com/earthobservations/wetterdienst
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open weather data for humans
  doc_url: https://wetterdienst.readthedocs.io/
  dev_url: https://github.com/earthobservations/wetterdienst

extra:
  recipe-maintainers:
    - kmuehlbauer
